name = "KnotTheory"
uuid = "215268c9-7579-426e-8b7c-a3dc27acd339"
authors = ["hyperpolymath"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
julia = "1.9"
JSON3 = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
